#! /bin/sh
### BEGIN INIT INFO
# Provides:          track
# Required-Start:    rim
# Required-Stop:
# Default-Start:     5
# Short-Description: Resource tracking 
### END INIT INFO

. /lib/lsb/init-functions

PROGRAM=trxmgr
PROGPATH=/sbin
SCRIPT=trxmgr
PIDFILE=/var/run/$PROGRAM.pid
DESCRIPTION="Resource tracker"

start_it()
{
	if [ -f /etc/default/$PROGRAM ]; then
		. /etc/default/$PROGRAM
	fi
	log_daemon_msg "Starting $DESCRIPTION" "$PROGRAM"
	if start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $PROGPATH/$PROGRAM -- $OPTIONS; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
    # if there is a flat conf file (produced by the handler on save) we need to 
    # monitor ...
    [ -f /etc/trxdbg.conf ] && echo "export LD_PRELOAD=trx.so" > /__setenv__
}

stop_it()
{
	log_daemon_msg "Stopping $DESCRIPTION" "$PROGRAM"
	pgid=`cat $PIDFILE`
	if [ "$pgid" ] && kill -0 -$pgid 2>/dev/null; then
	    kill -TERM -$pgid
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
}

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
    start_it
    ;;
  stop)
    stop_it
	;;
  restart)
	stop_it
    start_it
	;;

  status)
	status_of_proc -p $PIDFILE $PROGPATH/$PROGRAM $PROGRAM && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: /etc/init.d/$SCRIPT {start|stop|restart|status}"
	exit 1
esac

exit 0
