#!/usr/bin/env python

"""
Recover system from backup
"""
import backups
import sys
import os

if os.getuid() != 0:
    print "You must be root to run this command"
    sys.exit( 1 )
    
#
# test if remote access is setup
#
if os.system("testBackups xxx 2>/dev/null 1>&2") != 0:
    print "Remote access for backup has not been setup properly"
    print "Please configure backups and run 'testBackups' manually to set it up."
    sys.exit(1)

backup=backups.Backup();
bList=backup.getBackups()
if len(bList) > 1:
    print "%d backups found on server %s :\n" % (len(bList)-1, backup.getHost())
    for bname in bList:
        print "    %s" % bname
else:
    print "No backups were found on server %s :\n" % (backup.getHost())
    
sys.exit( 0 )
