#!/bin/sh
### BEGIN INIT INFO
# Provides:          postgres postgresql
# Required-Start:    rimpredb ntp
# Restart-with:		 ntp
# Default-Start:     3 5
# Default-Stop:      0 1 6
# Short-Description: Postgresql database common startup
# Description:       will start postgresql
### END INIT INFO
set -e

# Setting environment variables for the postmaster here does not work; please
# set them in /etc/postgresql/<version>/<cluster>/environment instead.

[ -r /usr/share/postgresql-common/init.d-functions ] || exit 0

. /usr/share/postgresql-common/init.d-functions

# versions can be specified explicitly
if [ -n "$2" ]; then
    versions="$2 $3 $4 $5 $6 $7 $8 $9"
else
    get_versions
fi

case "$1" in
    start|stop|restart|reload)
	for v in $versions; do
	    $1 $v
	done
        ;;
    status)
	set +e
	for v in $versions; do
	    ($1 $v)
	done
        ;;
    force-reload)
	for v in $versions; do
	    reload $v
	done
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|force-reload|status} [version ..]"
        exit 1
        ;;
esac

exit 0

